services:
  nginx-router:
    build: .
    container_name: nginx-router
    ports:
      - "80:80"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  coredns:
#    image: coredns/coredns
#    container_name: coredns
#    restart: always
#    volumes:
#      - ./Corefile:/etc/coredns/Corefile:ro
#      - ./kako.org.db:/etc/coredns/kako.org.db:ro
#    ports:
#      - "53:53/udp"
#      - "53:53/tcp"
#    command: -conf /etc/coredns/Corefile
